ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [

    path('welcome/', include('welcome.urls', namespace='welcomes')),
    path('', include('welcome.urls', namespace='welcome')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('ingresos/', include('ingreso_tecnicx.urls', namespace='ingreso_tecnicx')),
    path('tables/', include('tables.urls', namespace='tables')),
    path('google/', include('gsheets.urls')),
]

tables/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from tables import views
from tables.views import FHListView, DotacionListView, GeovictoriaListView

app_name = 'tables'
urlpatterns = [
    path('flota/', login_required(FHListView.as_view()), name='flota'),
    path('flota_tablero/', views.flota_tablero, name='flota_tablero'),
    path('ssoma_tablero/', views.ssoma_tablero, name='ssoma_tablero'),
    path('rrhh_tabla/', login_required(DotacionListView.as_view()), name='tabla_dotacion'),
    path('rrhh_tabla_geo/', login_required(GeovictoriaListView.as_view()), name='tabla_geo'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = 'welcomes'
urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('set_email/', views.set_email, name='set_email'),
    path('change_email/', views.change_email, name='change_email'),
    path('set_pass/', views.set_pass, name='set_pass'),
    path('change_pass/', views.change_pass, name='change_pass'),

]

welcome/models.py
from django.contrib.auth.models import User
import pandas as pd
# Create your models here.
from django.db import models


class CreateUsers:
    def __init__(self):
        self.file = pd.read_csv('Actualización Salfa - INDIRECTO.csv', usecols=['RUT', 'NOMBRE', 'CORREO'])

    def p(self):
        print(self.file.head())

    # it can be done with apply
    def creation(self):
        ruts = self.file['RUT'].unique()
        for rut in ruts:
            serie_rut = self.file.loc[self.file['RUT'].isin([rut])]
            email = str(serie_rut['CORREO'].to_numpy()[0])
            nombre_corto = str(serie_rut['NOMBRE'].to_numpy()[0])
            #nombre_corto = str(serie_rut['NOMBRE CORTO'].to_numpy()[0])
            user = User.objects.create_user(rut, email, rut.split('-')[0][-4:])
            user.first_name = nombre_corto.split()[0]
            user.last_name = nombre_corto.split()[1]
            user.save()

welcome/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


@login_required(login_url='')
def welcome(request):
    context = {'nbar': 'home'}
    return render(request, 'welcome/welcome.html', context=context)


@login_required(login_url='')
def set_email(request):
    return render(request, 'welcome/set_email.html')


@login_required(login_url='')
def change_email(request):
    email = request.POST['email']
    u = request.user
    u.email = email
    u.save()

    return HttpResponseRedirect(reverse('welcome:welcome'))


@login_required(login_url='')
def set_pass(request):
    form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'welcome/set_pass.html', context=context)


@login_required(login_url='')
def change_pass(request):
    pass1 = request.POST['new_password1']
    pass2 = request.POST['new_password2']
    valid = pass1 == pass2
    if valid:
        u = request.user
        u.set_password(pass1)
        u.save()
    context = {'valid': valid}
    return render(request, 'welcome/valid_pass.html', context=context)

welcome/templates/welcome/set_email.html
{% extends 'base.html' %}

{% block content %}

    <p>Escriba su nueva dirección de correo electrónico</p>
    <form action="{% url 'welcome:change_email' %}" method="post">
        {% csrf_token %}
        <label for="email">email:</label>
        <input type="text" id="email" name="email"><br><br>
        <input type="submit" value="Enviar">
    </form>

{% endblock %}

welcome/templates/welcome/set_pass.html
{% extends 'base.html' %}

{% block content %}

    <p>Please enter (and confirm) your new password.</p>
    <form action="{% url 'welcome:change_pass' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change my password" />
    </form>

{% endblock %}

welcome/templates/welcome/valid_pass.html
{% extends 'base.html' %}

{% block content %}

    {% if valid %}
        <p>Contraseña cambiada con éxito</p>
        <a href="{% url 'welcome:welcome' %}">Iniciar sesión</a>
    {% else %}
        <p>Formulario inválido, por favor intente nuevamente</p>
        <a href="{% url 'welcome:set_pass' %}">Volver</a>
    {% endif %}

{% endblock %}

welcome/templates/welcome/welcome.html
{% extends 'base.html' %}

{% block content %}

    <p>Welcome, {{ user.first_name }}. Thanks for logging in.</p>
    {% if user.email == "nan" %}
        <p>No tienes email registrado, haz click en 'Agregar email' para poder recuperar tu contraseña</p>
        <a href="{% url 'welcome:set_email' %}">Agregar email</a>
    {% else %}
        <p>Tu email es: {{ user.email }}</p>
        <a href="{% url 'welcome:set_email' %}">Cambiar email</a>
    {% endif %}
    <p></p>
    <a href="{% url 'welcome:set_pass' %}">Cambiar contraseña</a>
    <p></p>
    <a href="{% url 'logout' %}">Log out</a>

{% endblock %}