ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [

    path('welcome/', include('welcome.urls', namespace='welcomes')),
    path('', include('welcome.urls', namespace='welcome')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('ingresos/', include('ingreso_tecnicx.urls', namespace='ingreso_tecnicx')),
    path('tables/', include('tables.urls', namespace='tables')),
    path('google/', include('gsheets.urls')),
]

tables/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from tables import views
from tables.views import FHListView, DotacionListView, GeovictoriaListView

app_name = 'tables'
urlpatterns = [
    path('flota/', login_required(FHListView.as_view()), name='flota'),
    path('flota_tablero/', views.flota_tablero, name='flota_tablero'),
    path('ssoma_tablero/', views.ssoma_tablero, name='ssoma_tablero'),
    path('rrhh_tabla/', login_required(DotacionListView.as_view()), name='tabla_dotacion'),
    path('rrhh_tabla_geo/', login_required(GeovictoriaListView.as_view()), name='tabla_geo'),
]

tables/models.py
from compositefk.fields import CompositeForeignKey
from django.db import models

# Create your models here.

class db_flota(models.Model):
    jop = models.CharField(max_length=200)
    sup = models.CharField(max_length=200)
    rut = models.CharField(max_length=200)


class dotacion(models.Model):
    Rut = models.CharField(max_length=200, primary_key=True)
    Sigla = models.CharField(max_length=200)
    Nombre = models.CharField(max_length=200)
    Supervisor = models.CharField(max_length=200)
    Comuna = models.CharField(max_length=200)
    Zona = models.CharField(max_length=200)
    Cargo = models.CharField(max_length=200)
    Tipo = models.CharField(max_length=200)
    Tipo_ctto = models.CharField(max_length=200)
    Proyecto = models.CharField(max_length=200)
    Con_o_sin_experiencia = models.CharField(max_length=200)
    JOP = models.CharField(max_length=200)


class flota_FueraHorario(models.Model):
    Patente = models.CharField(max_length=200)
    proveedor = models.CharField(max_length=200)
    inicio = models.DateTimeField()
    fin = models.DateTimeField()
    eventos = models.DecimalField(max_digits=10, decimal_places=2)
    kms = models.DecimalField(max_digits=10, decimal_places=2)
    empleado = models.CharField(max_length=200)
    #matching = CompositeForeignKey(db_flota, on_delete=models.CASCADE, related_name='dd', to_fields={
     #   'jop': 'Patente',
      #  'sup': 'proveedor'
    #}
                     #              )


class geovictoriav2(models.Model):
    Apellidos = models.CharField(max_length=200)
    Nombre = models.CharField(max_length=200)
    Rut = models.ForeignKey(dotacion, on_delete=models.CASCADE)
    Grupo = models.CharField(max_length=200)
    Fecha = models.DateTimeField()
    Permiso = models.CharField(max_length=200)
    Turno = models.CharField(max_length=200)
    Entro = models.TimeField(auto_now=False, auto_now_add=False, default=None, blank=True, null=True)
    Salio = models.TimeField(auto_now=False, auto_now_add=False, default=None, blank=True, null=True)
    Cargo = models.CharField(max_length=200)

tables/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin
from django_tables2.export import ExportMixin

from tables.filters import FHFilter, DotFilter
from tables.models import flota_FueraHorario, dotacion, geovictoriav2
from tables.tables import FHTable, DotacionTable, GeovictoriaTable


class FHListView(ExportMixin, SingleTableMixin, FilterView):
    model = flota_FueraHorario
    table_class = FHTable
    template_name = 'flota/fuera_horario.html'
    filterset_class = FHFilter
    export_formats = ("latex", "csv", "xlsx")

    def get_table_kwargs(self):
        return {"template_name": "django_tables2/bootstrap.html"}


class DotacionListView(ExportMixin, SingleTableMixin, FilterView):
    model = dotacion
    table_class = DotacionTable
    template_name = 'rrhh/rrhh_tabla.html'
    filterset_class = DotFilter
    export_formats = ("latex", "csv", "xlsx")

    def get_table_kwargs(self):
        return {"template_name": "django_tables2/bootstrap.html"}


class GeovictoriaListView(ExportMixin, SingleTableMixin, FilterView):
    model = geovictoriav2
    table_class = GeovictoriaTable
    template_name = 'rrhh/rrhh_tabla.html'
    #filterset_class = FHFilter
    export_formats = ("latex", "csv", "xlsx")

    def get_table_kwargs(self):
        return {"template_name": "django_tables2/bootstrap.html"}


@login_required(login_url='')
def pag1(request):
    context = {'nbar': 'flota'}
    return render(request, 'flota/fuera_horario.html', context=context)


@login_required(login_url='')
def flota_tablero(request):
    return render(request, 'flota/tablero.html')


@login_required(login_url='')
def ssoma_tablero(request):
    context = {'nbar': 'ssoma'}
    return render(request, 'ssoma/tablero.html', context=context)

tables/templates/rrhh/rrhh_tabla.html
{% extends 'base.html' %}

{% block content %}

    {% load django_tables2 %}
    {% load render_table from django_tables2 %}
    {% load bootstrap3 %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <head>
        <title>Dotación</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>

    {% if filter %}
        <form action="" method="get" class="form form-inline">
            {% bootstrap_form filter.form layout='inline' %}
            {% bootstrap_button 'filter' %}
        </form>
    {% else %}
        <p>no hay filtros</p>
    {% endif %}

    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Elige tu base de datos
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><a href="{% url 'tables:tabla_dotacion' %}">Dotación</a></li>
        <li><a href="{% url 'tables:tabla_geo' %}">Geovictoria</a></li>
      </ul>
    </div>

    {% if view.export_formats %}
        {% for format in view.export_formats %}
            <a href="{% export_url format %}" class="btn btn-xs btn-default">
                download  <code>.{{ format }}</code>
            </a>
        {% endfor %}
    {% endif %}

    {% load render_table from django_tables2 %}
    <p> Tablas RR.HH. </p>

    <body>
        {% render_table table 'django_tables2/bootstrap.html' %}
    </body>

{% endblock %}