ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [

    path('welcome/', include('welcome.urls', namespace='welcomes')),
    path('', include('welcome.urls', namespace='welcome')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('ingresos/', include('ingreso_tecnicx.urls', namespace='ingreso_tecnicx')),
    path('tables/', include('tables.urls', namespace='tables')),
    path('google/', include('gsheets.urls')),
]

tables/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from tables import views
from tables.views import FHListView, DotacionListView, GeovictoriaListView

app_name = 'tables'
urlpatterns = [
    path('flota/', login_required(FHListView.as_view()), name='flota'),
    path('flota_tablero/', views.flota_tablero, name='flota_tablero'),
    path('ssoma_tablero/', views.ssoma_tablero, name='ssoma_tablero'),
    path('rrhh_tabla/', login_required(DotacionListView.as_view()), name='tabla_dotacion'),
    path('rrhh_tabla_geo/', login_required(GeovictoriaListView.as_view()), name='tabla_geo'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = 'welcomes'
urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('set_email/', views.set_email, name='set_email'),
    path('change_email/', views.change_email, name='change_email'),
    path('set_pass/', views.set_pass, name='set_pass'),
    path('change_pass/', views.change_pass, name='change_pass'),

]

templates/base.html
{% load static %}
{# Load the tag library #}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<link rel="stylesheet" type="text/css" href="{% static 'welcome/base.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<body>


<nav class="navbar navbar-default custom-navbar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
      <a class="navbar-brand" href="#">Proyecto django</a>
    </div>
      {% if user.is_authenticated %}
      <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
          <li class="{% if nbar == 'home' %}active{% endif %}"><a class="navbar-brand" href="{% url 'welcomes:welcome' %}">Perfil</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Planificación y control<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Tablero PBI</a></li>
              <li><a href="#">Base de datos</a></li>
            </ul>
          </li>

          <li class="dropdown" ><a class="dropdown-toggle" data-toggle="dropdown" href="#">Flota<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'tables:flota_tablero' %}">Tablero PBI</a></li>
              <li><a href="{% url 'tables:flota' %}">DB Flota</a></li>
            </ul>
          </li>

          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Calidad<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Tablero PBI</a></li>
              <li><a href="#">Base de datos</a></li>
            </ul>
          </li>

          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">RR.HH.<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Tablero PBI</a></li>
              <li><a href="{% url 'tables:tabla_dotacion' %}">Base de datos</a></li>
            </ul>
          </li>

          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">SSOMA<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'tables:ssoma_tablero' %}">Tablero PBI</a></li>
              <li><a href="#">Base de datos</a></li>
            </ul>
          </li>

          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Centro de comunicaciones<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Tablero PBI</a></li>
              <li><a href="#">Base de datos</a></li>
            </ul>
          </li>

          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Operación<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Tablero PBI</a></li>
              <li><a href="#">Base de datos</a></li>
            </ul>
          </li>

      </ul>
      </div>
        {% else %}
            <li><a href="{% url 'welcomes:welcome' %}">Iniciar Sesión</a></li>
        {% endif %}

  </div>
</nav>

<div class="block">
    {% block content %}
    {% endblock %}
</div>
</body>